from __future__ import annotations

import argparse
import json
from pathlib import Path
import shlex
import subprocess
import sys
from typing import Any

from .config import configure_agent, default_config, load_config, save_config
from .grapher import GrapherControlPlane
from .mission import AccessMode, CapabilitySet, Mission, MissionStatus, Source, SourceType


GENERATED_AGENT_MARKER = "<!-- dreadnought:generated-bootstrap -->"


def discover_project_roots(root: Path) -> list[Path]:
    """Discover plausible managed project roots immediately inside a workspace."""
    root = root.resolve()
    if (root / ".grapher" / "knowledge.json").is_file() or (root / ".git").exists():
        return [root]

    candidates: list[Path] = []
    if not root.exists():
        return candidates
    for child in sorted((path for path in root.iterdir() if path.is_dir()), key=lambda path: path.name):
        if child.name.startswith("."):
            continue
        if (child / ".grapher" / "knowledge.json").is_file() or (child / ".git").exists():
            candidates.append(child.resolve())
    return candidates


def resolve_project_root(root: Path, requested: str | Path | None = None) -> Path:
    root = root.resolve()
    if requested is not None:
        candidate = Path(requested)
        if not candidate.is_absolute():
            candidate = root / candidate
        candidate = candidate.resolve()
        try:
            candidate.relative_to(root)
        except ValueError as exc:
            raise ValueError("managed project root must be inside the Dreadnought workspace") from exc
        if not candidate.is_dir():
            raise ValueError(f"managed project root does not exist: {candidate}")
        return candidate

    candidates = discover_project_roots(root)
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        return root
    names = ", ".join(path.name for path in candidates)
    raise ValueError(f"multiple project roots detected ({names}); select one with --project-root")


def _project_ref(root: Path, project_root: Path) -> str:
    try:
        relative = project_root.resolve().relative_to(root.resolve())
    except ValueError:
        return str(project_root.resolve())
    return "." if relative == Path(".") else str(relative)


def _write_bootstrap_mission(
    root: Path,
    project_root: Path,
    *,
    directive: str,
    objective: str,
    requirements: list[str],
    actor: str,
    brain_mode: str,
) -> tuple[Mission, Path]:
    mission = Mission.draft(directive=directive, workspace=str(root), actor_id=actor)
    mission.objective = objective.strip() or directive.strip()
    mission.requirements = [item.strip() for item in requirements if item.strip()]
    mission.capabilities = CapabilitySet(
        canonical_workspace=AccessMode.PROPOSE_WRITE,
        scratch_write=True,
        git_inspect=True,
        git_propose_commit=True,
        git_push=False,
        network="brokered",
        shell="restricted",
        max_minions=0,
    )
    mission.sources.append(
        Source(
            id="workspace-1",
            type=SourceType.WORKSPACE,
            locator=str(project_root),
            access=AccessMode.READ,
        )
    )
    mission.human_notes.append(f"Bootstrap brain mode: {brain_mode}")
    mission.status = MissionStatus.READY
    errors = mission.validate()
    if errors:
        raise ValueError("invalid bootstrap mission: " + "; ".join(errors))
    path = root / ".dreadnought" / "missions" / f"{mission.id}.json"
    mission.write(path)
    return mission, path


def render_instructions(
    root: Path,
    project_root: Path,
    mission: Mission,
    brain: dict[str, Any],
) -> str:
    requirements = "\n".join(f"- {item}" for item in mission.requirements) or "- No additional operator requirements were supplied at bootstrap."
    inherited = "yes" if brain.get("mode") == "adopted" else "no"
    return f"""# Dreadnought workspace instructions

Generated by `dreadnought initialize` from the operator's bootstrap intent.

## Workspace identity

- Dreadnought workspace: `{root}`
- Managed project root: `{project_root}`
- Bootstrap mission: `{mission.id}`
- Grapher mode: `{brain.get('mode', 'unknown')}`
- Inherited Grapher history: `{inherited}`

## Operator directive

{mission.directive}

## Primary objective

{mission.objective}

## Requirements and constraints

{requirements}

## Authority model

- Dreadnought is the control plane for this workspace.
- Grapher is the durable project brain and remains independently usable outside Dreadnought.
- Inside this workspace, Dreadnought is the sole authority that mutates Grapher.
- Every substantive repository change must invoke Grapher through Dreadnought before it is complete; hand-authored Grapher evidence or pass records are not a substitute.
- Project Arms / Sarcophagus agents may receive brokered Grapher context and return typed testimony, but they do not write Grapher directly.
- Agent testimony is not observer truth and successful execution is not automatic acceptance.

## Inherited-state rule

When an existing Grapher brain is adopted, preserve its historical nodes and provenance. Do not rewrite old workspace paths, statuses, or conclusions merely to make them look current. New work must establish new mission-scoped evidence and supersede legacy claims explicitly when warranted.

## Working rule

Before acting, inspect the bootstrap Mission and relevant Grapher context. Every substantive repository change must use Grapher through Dreadnought to record durable decisions, observations, implementation results, evidence, and supersession. Shared evidence files and chat history may supplement that record but cannot replace the Grapher mutation.
"""


def _write_generated_instructions(root: Path, content: str) -> tuple[Path, Path | None]:
    instructions = root / ".dreadnought" / "INSTRUCTIONS.md"
    instructions.parent.mkdir(parents=True, exist_ok=True)
    instructions.write_text(content.rstrip() + "\n", encoding="utf-8")

    agent_entry = root / "AGENTS.md"
    pointer = (
        f"{GENERATED_AGENT_MARKER}\n"
        "# Dreadnought workspace entrypoint\n\n"
        "Read `.dreadnought/INSTRUCTIONS.md` before planning or executing work in this workspace. "
        "Dreadnought owns Grapher mutation authority; subordinate agents must use the Dreadnought control plane. "
        "Every substantive repository change must invoke Grapher through Dreadnought; shared evidence alone is insufficient.\n"
    )
    if not agent_entry.exists():
        agent_entry.write_text(pointer, encoding="utf-8")
        return instructions, agent_entry
    existing = agent_entry.read_text(encoding="utf-8")
    if GENERATED_AGENT_MARKER in existing:
        agent_entry.write_text(pointer, encoding="utf-8")
        return instructions, agent_entry
    return instructions, None


def bootstrap_workspace(
    root: Path | str,
    *,
    directive: str,
    objective: str | None = None,
    requirements: list[str] | None = None,
    actor: str = "human:user",
    project_id: str | None = None,
    project_root: str | Path | None = None,
    agent_type: str | None = None,
    agent_executable: str | None = None,
    agent_args: list[str] | None = None,
) -> dict[str, Any]:
    root = Path(root).resolve()
    root.mkdir(parents=True, exist_ok=True)
    managed = resolve_project_root(root, project_root)

    config = load_config(root) if (root / ".dreadnought" / "config.json").exists() else default_config(root)
    config["project_id"] = (project_id or managed.name or root.name).strip()
    config["project_root"] = _project_ref(root, managed)
    save_config(root, config)

    plane = GrapherControlPlane(root)
    if plane.graph_path.exists():
        brain = plane.adopt()
    else:
        graph_path = plane.initialize()
        doctor = plane.doctor()
        brain = {
            "mode": "initialized",
            "graph_path": str(graph_path),
            "graph_version": doctor.get("graph_version"),
            "existing_nodes": 0,
            "legacy_unclassified_allowlisted": 0,
            "compatible": bool(doctor.get("compatible")),
        }

    mission, mission_path = _write_bootstrap_mission(
        root,
        managed,
        directive=directive,
        objective=objective or directive,
        requirements=list(requirements or []),
        actor=actor,
        brain_mode=str(brain["mode"]),
    )
    instructions_content = render_instructions(root, managed, mission, brain)
    instructions_path, agent_entry = _write_generated_instructions(root, instructions_content)

    config = load_config(root)
    config["bootstrap_mission"] = mission.id
    config["instructions_path"] = str(instructions_path.relative_to(root))
    config["grapher_mode"] = brain["mode"]
    save_config(root, config)

    if agent_type and agent_type != "none":
        configure_agent(
            root,
            agent_type=agent_type,
            executable=agent_executable,
            args=list(agent_args or []),
            primary=True,
        )

    final_config = load_config(root)
    return {
        "root": str(root),
        "project_id": final_config["project_id"],
        "project_root": str(managed),
        "mission": mission.id,
        "mission_path": str(mission_path),
        "instructions": str(instructions_path),
        "agent_entrypoint": str(agent_entry) if agent_entry else None,
        "brain": brain,
        "grapher": GrapherControlPlane(root).doctor(),
        "primary_agent": final_config.get("primary_agent"),
    }


def _choose_project_root(root: Path, requested: str | None) -> Path:
    if requested:
        return resolve_project_root(root, requested)
    candidates = discover_project_roots(root)
    if len(candidates) <= 1:
        return resolve_project_root(root)

    from .interactive import choose

    options = [(_project_ref(root, path), _project_ref(root, path)) for path in candidates]
    selected = choose("Dreadnought setup", "Managed project root", options)
    if not selected:
        raise ValueError("project selection cancelled")
    return resolve_project_root(root, selected)


def _launch_primary_agent(root: Path) -> int:
    config = load_config(root)
    agent_type = config.get("primary_agent")
    agent = (config.get("agents") or {}).get(agent_type) if agent_type else None
    if not agent:
        print("no primary Dreadnought agent configured", file=sys.stderr)
        return 2
    command = [agent["executable"], *list(agent.get("args") or [])]
    try:
        return subprocess.call(command, cwd=root)
    except FileNotFoundError:
        print(f"agent executable not found: {agent['executable']}", file=sys.stderr)
        return 2


def run_bootstrap_cli(argv: list[str], *, prog: str = "dreadnought initialize") -> int:
    parser = argparse.ArgumentParser(prog=prog, description="Initialize or adopt a Dreadnought workspace from human intent")
    parser.add_argument("brief", nargs="?", help="bootstrap directive / human intent")
    parser.add_argument("--directive", help="bootstrap directive (alternative to positional brief)")
    parser.add_argument("--objective")
    parser.add_argument("--requirement", action="append", default=[])
    parser.add_argument("--root", default=".")
    parser.add_argument("--project-id")
    parser.add_argument("--project-root")
    parser.add_argument("--actor", default="human:user")
    parser.add_argument("--agent-type")
    parser.add_argument("--agent-executable")
    parser.add_argument("--agent-arg", action="append", default=[])
    parser.add_argument("--chat", action="store_true")
    parser.add_argument("--non-interactive", action="store_true")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    root.mkdir(parents=True, exist_ok=True)
    interactive = not args.non_interactive and sys.stdin.isatty() and sys.stdout.isatty()
    directive = (args.directive or args.brief or "").strip()
    objective = (args.objective or "").strip()
    project_id = args.project_id
    project_root = args.project_root
    agent_type = args.agent_type
    agent_executable = args.agent_executable
    agent_args = list(args.agent_arg or [])
    chat_now = bool(args.chat)

    if interactive:
        from .interactive import ask, choose, confirm, show

        managed = _choose_project_root(root, project_root)
        project_root = _project_ref(root, managed)
        project_id = ask("Dreadnought setup", "Project ID", project_id or managed.name) or managed.name
        directive = ask("Dreadnought setup", "Bootstrap directive / human intent", directive) or directive
        if not directive:
            show("Dreadnought setup", "A bootstrap directive is required.")
            return 2
        objective = ask("Dreadnought setup", "Primary objective", objective or directive) or directive
        if agent_type is None:
            agent_type = choose(
                "Dreadnought setup",
                "Primary Dreadnought agent",
                [("codex", "Codex"), ("cursor", "Cursor"), ("custom", "Custom command"), ("none", "Configure later")],
            )
        if agent_type and agent_type != "none":
            defaults = {"codex": "codex", "cursor": "agent", "custom": ""}
            agent_executable = ask("Dreadnought setup", "Agent executable", agent_executable or defaults.get(agent_type, agent_type))
            arg_text = ask("Dreadnought setup", "Chat arguments (optional)", " ".join(agent_args)) or ""
            agent_args = shlex.split(arg_text)
            chat_now = confirm("Dreadnought setup", "Open the primary agent chat after bootstrap?")
    elif not directive:
        directive = f"Establish Dreadnought control for {project_id or root.name}."
        objective = objective or directive

    try:
        result = bootstrap_workspace(
            root,
            directive=directive,
            objective=objective or directive,
            requirements=list(args.requirement or []),
            actor=args.actor,
            project_id=project_id,
            project_root=project_root,
            agent_type=agent_type,
            agent_executable=agent_executable,
            agent_args=agent_args,
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        if interactive:
            from .interactive import show
            show("Dreadnought setup failed", str(exc))
        else:
            print(f"dreadnought bootstrap failed: {exc}", file=sys.stderr)
        return 2

    if interactive:
        from .interactive import show
        show("Dreadnought ready", json.dumps(result, indent=2))
    else:
        print(json.dumps(result, indent=2))
    if chat_now and result.get("primary_agent"):
        return _launch_primary_agent(root)
    return 0


def run_home_menu(root: Path | None = None) -> int:
    from .interactive import ask, choose, show
    from .mission_builder import mission_menu
    from .usage import TokenUsageLedger

    root = (root or Path.cwd()).resolve()
    while True:
        action = choose(
            "Dreadnought",
            f"Workspace: {root}",
            [
                ("init", "Initialize / adopt workspace"),
                ("missions", "Missions"),
                ("chat", "Chat with primary Dreadnought agent"),
                ("query", "Query Grapher brain"),
                ("usage", "Token usage statistics"),
                ("config", "Show project configuration"),
                ("exit", "Exit"),
            ],
        )
        if action in {None, "exit"}:
            return 0
        if action == "init":
            run_bootstrap_cli(["--root", str(root)])
        elif action == "missions":
            mission_menu(root)
        elif action == "chat":
            rc = _launch_primary_agent(root)
            if rc:
                show("Agent chat", "Primary agent is not configured or could not launch.")
        elif action == "query":
            text = ask("Grapher", "Search query", "")
            if text:
                try:
                    hits = GrapherControlPlane(root).query(text, limit=10)
                    show("Grapher results", json.dumps(hits, indent=2)[:12000])
                except (OSError, ValueError) as exc:
                    show("Grapher query", str(exc))
        elif action == "usage":
            show("Token usage", json.dumps(TokenUsageLedger(root).stats(), indent=2))
        elif action == "config":
            show("Configuration", json.dumps(load_config(root), indent=2, sort_keys=True))
